### ISSUE TITLE
travis-ci issues

### ISSUE THREAD

**Issue by jgabry** [stan-dev/bayesplot#102]
Travis-ci hasn't been working for **bayesplot** recently, apparently because it has been having trouble installing **rstan** and **rstanarm**. The source code in **bayesplot** is independent of **rstan** and **rstanarm** but it does use those packages in tests and vignettes. 

I'm not much of a travis expert, but the problem seems to be with compiling **rstan**. When this happens there is typically a message somewhere in the travis log like: 

```
ERROR: compilation failed for package ‘rstan’
* removing ‘/home/travis/R/Library/rstan’
Installation failed: Command failed (1)
```

If this can be resolved soon then continuing to use travis seems fine. But if this is going to be a problem going forward then I see three options, each of which has a downside: 

* Use a different continuous integration service if there is one that will work (obvious downside here is having to find something else that works and get it set up)
* Stop using **rstanarm** in tests and stop using **rstanarm** and **rstan** in vignettes (this is not preferable because it's very useful to have these in the tests and vignettes)
* Don't have travis check the vignettes and also have it ignore tests that use these packages  (this is probably the simplest solution but I would very much prefer for travis to be checking everything)

**Comment by tjmahr** [comment]
Hmm I was going to suggest that we just copy what brms is doing in its .travis.yml file because its builds look successful. But [rstan fails to compile in brms builds too](https://travis-ci.org/paul-buerkner/brms/builds/260754168#L792-L794). They just have a good version of rstan cached that the builds fall back to.

**Comment by jgabry** [comment]
Good idea to check brms. Bummer that travis seems to be failing to compile
rstan for everyone. It'd be great if we can get  Travis working but there
might be a different solution on its way. @bgoodri is looking into setting
up Jenkins on some machines we have at Columbia, so if that works we should
be able to use it instead of travis for CI for all of our  R packages.

**Comment by bob-carpenter** [comment]
You should talk to @seantalts, as he had to reconfigure the stan-dev/math and stan-dev/stan configs after Travis changed their config.

**Comment by seantalts** [comment]
One of the main things I had to do was adapt things to Trusty, which they moved over to from Precise recently. But the build that tjmahr linked to above had brms failing to build rstan on Precise as well. Have you guys tried `dist: trusty`? You might give that a shot and see what happens.

**Comment by bgoodri** [comment]
Travis in principle could build it usually, but would almost always time
out (even after we gave it more time) or fail for some reason unrelated to
the R package in question.

**Comment by seantalts** [comment]
Also not sure if you guys saw this, but here's the error message it's getting:
```
g++  -I/home/travis/R-bin/lib/R/include -DNDEBUG -I"../inst/include" -I"../inst/include/boost_not_in_BH" -I"`"/home/travis/R-bin/lib/R/bin/Rscript" --vanilla -e "cat(system.file('include', 'src', package = 'StanHeaders'))"`" -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -DFUSION_MAX_VECTOR_SIZE=12 -I"/home/travis/R/Library/Rcpp/include" -I"/home/travis/R/Library/RcppEigen/include" -I"/home/travis/R/Library/BH/include" -I"/home/travis/R/Library/StanHeaders/include" -I/home/travis/R-bin/include   -fpic  -g -O2  -c lang__ast_def.cpp -o lang__ast_def.o
In file included from /home/travis/R/Library/StanHeaders/include/src/stan/lang/ast.hpp:68:0,
                 from /home/travis/R/Library/StanHeaders/include/src/stan/lang/ast_def.cpp:7,
                 from lang__ast_def.cpp:18:
/home/travis/R/Library/StanHeaders/include/src/stan/lang/ast/node/conditional_op.hpp:40:23: error: ISO C++ forbids initialization of member ‘has_var_’ [-fpermissive]
/home/travis/R/Library/StanHeaders/include/src/stan/lang/ast/node/conditional_op.hpp:40:23: error: making ‘has_var_’ static [-fpermissive]
/home/travis/R/Library/StanHeaders/include/src/stan/lang/ast/node/conditional_op.hpp:40:23: error: ISO C++ forbids in-class initialization of non-const static member ‘has_var_’
make: *** [lang__ast_def.o] Error 1
ERROR: compilation failed for package ‘rstan’
```

The default g++ on Travis' Precise distro is pretty old. If it's an issue of an old compiler I can definitely help you guys with that.

**Comment by bgoodri** [comment]
This particular thing is fixed in develop.

**Comment by seantalts** [comment]
I don't actually see a develop branch on github...

**Comment by bgoodri** [comment]
I meant the develop branch of Stan when packaged into StanHeaders fixes it.

**Comment by jgabry** [comment]
closed that by mistake, reopening

**Comment by jgabry** [comment]
travis has actually been working ok for bayesplot recently so I'm go close this for now. Will reopen if (when?) problems arise again.
