### ISSUE TITLE
refactor mcmc_intervals/mcmc_areas

### ISSUE THREAD

**Issue by jgabry** [stan-dev/bayesplot#103]
These are based on very old code and the same functionality could be provided using less code (and simpler code). Some improvements could be made too, for example using a discrete scale for the vertical axis.

**Comment by tjmahr** [comment]
Just some notes from studying the code.

Right now, we call `mcmc_intervals()` and `mcmc_areas()`, and that prepares a call to the workhorse function `.mcmc_intervals()`. That function prepares the data for both types of plots, creating the density curves based on a flag `show_density` if needed, and then produces the plots.

I will first factor out the data-preparation steps and export new functions `mcmc_intervals_data()` and `mcmc_areas_data()`.

**Comment by jgabry** [comment]
Sounds great! These two functions are probably the worst in the package
from a coding perspective, so there's a chance it will take less time to
implement the functionality from scratch than to try to modify the existing
code. If I were going to do it myself that's what I might do, but however
you want to go about it is fine by me!

On another note, since it would be good to eventually offer joy plots it
might make sense to keep that in the back of your mind when working on the
intervals and areas functions. I would think that a joy plot implementation
could share some of the same internals.
