### ISSUE TITLE
Error in Ops.unit

### ISSUE THREAD

**Issue by mattwilliamson13** [stan-dev/bayesplot#106]
Running some of the examples in the bayesplot help vignette results in an error:
`Error in Ops.unit(theme$legend.spacing.y %||% 0.5, unit(title_height,  : 
  only one operand may be a unit`

This error seems to show up when running:
`ppc_stat(y, yrep, stat = "median") + grid_lines()`
and

`mcmc_recover_hist(
    y_ppcs[, c(5, 10, 15, 20)], true = db.stan$brte[c(5, 10, 15, 20)] )`

There may be others - I'll add them to this issue if I find them.

**Comment by mattwilliamson13** [comment]
also happens `with ppc_stat()`

**Comment by tjmahr** [comment]
Hmmm I can't replicate any of these errors running on the latest github version or the CRAN version.

To run all the code in the examples mentioned:

```r
example("MCMC-recover", package = "bayesplot", 
        run.dontrun = TRUE, run.donttest = TRUE)

example("bayesplot-package", package = "bayesplot", 
        run.dontrun = TRUE, run.donttest = TRUE)

example("PPC-test-statistics", package = "bayesplot", 
        run.dontrun = TRUE, run.donttest = TRUE)
```

**Comment by mattwilliamson13** [comment]
Is it possibly due to the fact that I'm using the dev version of ggplot2?

**Comment by tjmahr** [comment]
Okay. I get the error when I use tidyverse/ggplot2@c592e3240beae5991a095aae06c02ce3fcfe571c. 

```
example("PPC-test-statistics", package = "bayesplot", run.dontrun = TRUE, run.donttest = TRUE)

PPC-t-> y <- example_y_data()

PPC-t-> yrep <- example_yrep_draws()

PPC-t-> ppc_stat(y, yrep)
Hit <Return> to see next plot: 
`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
Error in Ops.unit(theme$legend.spacing.y %||% 0.5, unit(title_height,  : 
  only one operand may be a unit
```
Downgrading back to CRAN version fixes it.

I might have to bother @karawoo about this.

**Comment by tjmahr** [comment]
I reported it to ggplot2. We can close this issue because it only happens when some with bayesplot installs a dev version of ggplot2.

**Comment by jgabry** [comment]
Matt, thanks for filing the issue.

TJ, thanks for looking into this and reporting to ggplot2. Assuming this
isn't a problem when the next ggplot2 is actually released (i.e. that they
fix it before then) then yeah I think we can leave bayesplot as is. If
they're actually going to break this in the ggplot2 release then we can
revisit and change whatever we need to.

**Comment by mattwilliamson13** [comment]
Dumb question, but I can't seem to figure out how to revert back to the old version... I've tried re-installing from Cran (rather than github), but the development version continues to load.

 FWIW I installed the newer version to be able to use `geom_sf()` from the `sf` package for some of the new mapping capabilities in ggplot, not sure why any of that affects bayesplot calls...

Thanks for your help!

**Comment by tjmahr** [comment]
Not dumb a question. To revert, I started a new R session and then did `install.packages("ggplot2")`. If bayesplot or ggplot2 was already loaded, it wouldn't work, so I made sure to use a fresh R session.

**Comment by mattwilliamson13** [comment]
Awesome - got it fixed. Error no longer appears. Should I close this or do you want it left open until the ggplot folks respond?

**Comment by tjmahr** [comment]
Closing because this is a ggplot2 issue.
