### ISSUE TITLE
codecov failing recently

### ISSUE THREAD

**Issue by jgabry** [stan-dev/bayesplot#114]
If you look at the end any recent travis log for bayesplot, travis has been building and checking fine but the `after_success` part where it links up with codecov.io hasn't been working. Below is the relevant part from travis but you can also see that  https://codecov.io/gh/stan-dev/bayesplot is not at all up to date.

```
[0Ktravis_fold:start:after_success
[0Ktravis_time:start:12f8b8d5
[0K$ Rscript -e 'covr::codecov()'
Error: Failure in `/tmp/RtmpLqZpSD/R_LIBS29c236820e8f/bayesplot/bayesplot-tests/testthat.Rout.fail`
> library(testthat)
> library(bayesplot)
This is bayesplot version 1.4.0
- Plotting theme set to bayesplot::theme_default()
- Online documentation at mc-stan.org/bayesplot
> 
> Sys.unsetenv("R_TESTS")
> test_check("bayesplot")
Error in new_CppObject_xp(fields$.module, fields$.pointer, ...) : 
  no valid constructor available for the argument list
trying deprecated constructor; please alert package maintainer
Error: Can't find `tests/testthat/` in current directory.
testthat results ================================================================
OK: 454 SKIPPED: 0 FAILED: 0
Execution halted
Execution halted
```

I don't understand the reason for this particular error:
```
Error: Can't find `tests/testthat/` in current directory.
```

@tjmahr Any ideas about this?

**Comment by tjmahr** [comment]
Would the errors have something to do with it?

```
Error in new_CppObject_xp(fields$.module, fields$.pointer, ...) : 
  no valid constructor available for the argument list
```

Just a few days ago, it failed without the testthat error: https://travis-ci.org/stan-dev/bayesplot/jobs/273109927

```
$ Rscript -e 'covr::codecov()'
Error: Failure in `/tmp/Rtmp6Vogj1/R_LIBS74bd1ff53ede/bayesplot/bayesplot-tests/testthat.Rout.fail`
> library(testthat)
> library(bayesplot)
This is bayesplot version 1.3.0.9000
- Plotting theme set to bayesplot::theme_default()
- Online documentation at mc-stan.org/bayesplot
> 
> Sys.unsetenv("R_TESTS")
> if (!grepl("^sparc",  R.version$platform))
+   test_check("bayesplot")
Error in new_CppObject_xp(fields$.module, fields$.pointer, ...) : 
  no valid constructor available for the argument list
trying deprecated constructor; please alert package maintainer
Error in new_CppObject_xp(fields$.module, fields$.pointer, ...) : 
  no valid constructor available for the argument list
trying deprecated constructor; please alert package maintainer
Error in new_CppObject_xp(fields$.module, fields$.pointer, ...) : 
  no valid constructor available for the argument list
trying deprecated constructor; please alert package maintainer
Error in new_CppObject_xp(fields$.module, fields$.pointer, ...) :
Execution halted
```

Can you get `covr::package_coverage(quiet = FALSE)` to run locally? I can't.

**Comment by jgabry** [comment]
I guess it's possible that those errors are the problem. I was thinking not
because (1) they don't cause any test failures (they aren't real errors)
and (2) the covr/codecov failure doesn't seem to occur after the first one
of those (there are multiple so it seems to keep running after at least a
few of those).

Even if it's not the problem here @bgoodri and I really need to get an
rstanarm release out asap so those messages go away. They can be safely
ignored but they sure look alarming to users! There's an rstan release
coming soon once a few kinks are worked out and then we'll get rstanarm
out.

Anyway, I'll see if I can get covr to run locally. I assume it won't work
if it doesn't for you but maybe it will be easier to figure out the problem
that way.

**Comment by jgabry** [comment]
I can't get it to run locally either. I did figure out that the error is coming from  `tools::testInstalledPackage`, which `covr::package_coverage` calls internally. That is, I can reproduce the error calling `tools::testInstalledPackage` directly. But I can't yet figure out why it's happening.

**Comment by jgabry** [comment]
I can also confirm that these pseudo errors from rstanarm
```
Error in new_CppObject_xp(fields$.module, fields$.pointer, ...) : 
  no valid constructor available for the argument list
trying deprecated constructor; please alert package maintainer
```

are _not_ the issue. I removed all of the test files that use rstanarm but when I run `covr::package_coverage(quiet = FALSE)` it still fails with

```
Error: Can't find `tests/testthat/` in current directory.
```

**Comment by jgabry** [comment]
I figured it out. The problem seems to be the usage of `testthat::test_path` inside test files. `test_path` looks for a `tests/testthat` directory but `tools::testInstalledPackage` (which is called by `covr::package_coverage`) runs the tests in a `bayesplot-tests` subdirectory (or in general in `pkg-tests`), so it results in the error we've been seeing. I can successfully run everything if I remove all cases of `test_path`. 

The strange thing about this is that I can't believe we're the first package to run into this problem but I haven't been able to find much about it online. Is nobody who uses `covr` also using `testthat::test_path`? That would surprise me. I guess I'll open an issue at https://github.com/r-lib/covr .

**Comment by tjmahr** [comment]
Whoa, I can't believe was test_path()!

**Comment by jgabry** [comment]
I know me neither!

**Comment by jgabry** [comment]
I'm going to push a commit that removes the usage of `test_path` so we can get code coverage working again. I guess we can go back to using `test_path` (which is really convenient!) if we find a solution.

**Comment by jgabry** [comment]
It was pointed out over at https://github.com/r-lib/covr/issues/283 that this was fixed in the development version of testthat https://github.com/hadley/testthat/issues/542, but it looks like it was almost a year ago and there hasn't been a testthat release since then. I guess whenever Hadley does end up releasing it we can go back to using `test_path`.

**Comment by tjmahr** [comment]
We could try the following setting in the travis config

```
r_github_packages: 
 - hadley/testthat
 - r-lib/covr
```

To install the development versions of the packages during the travis build...

**Comment by jgabry** [comment]
Yeah I guess that's probably fine. I'd be less inclined to do that if the
development version of testthat was changing frequently, but It's very
stable. And test_path is quite convenient.

**Comment by jgabry** [comment]
Ok, I updated to development version of testthat on my computer and ran `package_coverage` and it does seem to be fixed. I'll go ahead and revert the commit that removes the usage `test_path` and change the `travis.yml` file to install testthat from GitHub.

**Comment by jgabry** [comment]
And while I'm at it I'm going to put `test_path` in the remaining test files too (only some currently have it). If we're using it at all we might as well use it in all the test files.

**Comment by jgabry** [comment]
Done in 434249a593c9a69a2522f073383ab3b4ee94902b
