### ISSUE TITLE
copy/move `rhat()` and `neff_ratio()` to rstan(arm)?

### ISSUE THREAD

**Issue by strengejacke** [stan-dev/bayesplot#119]
I was looking for functions to extract rhat and the ratio for number of effective samples, and found those in the brms-package for brmsfit-objects, but not in rstan or rstanarm for stanreg-objects (where I would expect those functions to be).

Instead, I later realized that these are in the bayesplot-pkg. Wouldn't it make more sense to have the functions (also) in rstan/rstanarm as well?

**Comment by tjmahr** [comment]
@jgabry would the generics go in rstantools and the S3 methods go into rstan and rstanarm? I'm not sure about the stanverse organization in this regard.

**Comment by avehtari** [comment]
I think these are now in `posterior`. Maybe this issue can be closed?

**Comment by strengejacke** [comment]
Yes, I think so, too.
