### ISSUE TITLE
ppc-intervals label:"new plot" 

### ISSUE THREAD

**Issue by virgile-baudrot** [stan-dev/bayesplot#122]
I propose a variation of the `ppc-intervals` plot with observation `y` on the *x-axis* and and prediction `yrep` on the *y-axis*.
Here is the plot as it is now:
![rplot_ppc-intervals](https://user-images.githubusercontent.com/6065464/32106673-9fc1613a-bb2c-11e7-8c72-1d462396ba11.png)

And I propose this representation:
![rplot_ppc-intervals_2](https://user-images.githubusercontent.com/6065464/32106690-a950b4e4-bb2c-11e7-8426-fedc9010ee12.png)
The line is the $y=x$ line, which allows to easily detect the potential outliers.

We could also do that for grouped situations:
Original:
![rplot_ppc-intervals-grouped](https://user-images.githubusercontent.com/6065464/32106863-342dc804-bb2d-11e7-9ef6-30636e92e640.png)

Proposition:
![rplot_ppc-intervals-grouped_2](https://user-images.githubusercontent.com/6065464/32106869-3951f7c4-bb2d-11e7-86c1-100aeb9dee18.png)

And, maybe we could also use the argument `x` already present in `ppc-intervals` to labels points and see where problems are:
![rplot_ppc-intervals-grouped_2_labels](https://user-images.githubusercontent.com/6065464/32106963-7f58e246-bb2d-11e7-8787-ccfaf2665a1e.png)

So. If you think it could be good. I did a [fork of bayesplot here](https://github.com/virgile-baudrot/bayesplot). The only think that changed is a part in the `ppc-intervals.R` file. I called the function `ppc-intervals_2` as it is the same code ; but maybe it's not a good idea. Also, maybe there is a better way to do the trick. Let me know

**Comment by virgile-baudrot** [comment]
Well, I just realized that something similar was already possible if we set `x = y`

> ppc_intervals(y, yrep, y)
![rplot_ppc-intervals_xisy](https://user-images.githubusercontent.com/6065464/32109273-83ddcf82-bb34-11e7-894c-fd6d8802e1c3.png)

So don't know if my plot is still so relevant!

**Comment by jgabry** [comment]
Sorry for the slow response. I'm in the process of working through a lot of issues that have built up. If you add `x=y` like you did it will draw the points and you can also put a line through those points using bayesplot's `abline_01` helper function like this: 

```r
y <- rnorm(50)
yrep <- matrix(rnorm(5000, 0, 2), ncol = 50)

ppc_intervals(y, yrep, x = y) + abline_01()
```

![image](https://user-images.githubusercontent.com/7796803/36043030-eb916e40-0d9b-11e8-836d-13aaafba26cf.png)

I could add an option to do this automatically but since it's pretty easy I think I'll just add an example of how to do it to the documentation. Thanks for the suggestion!

**Comment by jgabry** [comment]
Closing this because I just added an example of doing this to the documentation in 62ff9b2. @virgile-baudrot thanks for suggesting this!
