### ISSUE TITLE
start adding visual unit tests

### ISSUE THREAD

**Issue by tjmahr** [stan-dev/bayesplot#124]
Use the [vdiffr package](https://github.com/lionel-/vdiffr).

Set up a few tests.

- [x] add new testing infrastructure to package
- [x] write minimal internal documentation.

Add tests for a few functions to practice how it works.

- [x] `mcmc_intervals()`
- [x] `mcmc_areas()`
- [x] `mcmc_areas_ridges()`
- [x] `mcmc_rhat()`
- [x] `mcmc_rhat_hist()`
- [x] `mcmc_neff()`
- [x] `mcmc_neff_hist()`

**Comment by tjmahr** [comment]
Some notes.

- Reference images are stored in `tests/figs/[testthat context]`.
- `vdiffr::expect_doppelganger("plot title", plot)` to compare the `plot` with the one saved in the collection of reference images. The test is skipped when there is no reference image.
- `vdiffr::collect_cases()` will run through the tests and create new reference images.
- `vdiffr::manage_cases()` opens a shiny app so you can see visual diffs of plots

![image](https://user-images.githubusercontent.com/1890315/32952851-0e820834-cb74-11e7-93b1-3450dcc7b0eb.png)

- Clicking "validate" will confirm the changes to a plot and update the reference version.
- There is a file called `test/figs/deps.txt` that stores dependency versions. Tests will be skipped when there is a version difference in the testing computer and the `deps` file.

**Comment by jgabry** [comment]
This is cool. I had seen mention of vdiffr but I’ve never played around
with it. Testing the plots themselves is something that I’ve wanted to do
though, so I’m definitely in favor of using this.
