### ISSUE TITLE
fix touching on mcmc_areas() plots

### ISSUE THREAD

**Issue by tjmahr** [stan-dev/bayesplot#125]
I got this when generating reference images for visual test.

![image](https://user-images.githubusercontent.com/1890315/32953255-40c0822a-cb75-11e7-9d62-e39de822c4ef.png)

Not good.

![No touching!](https://user-images.githubusercontent.com/1890315/32953291-5ca98e78-cb75-11e7-8768-0aa152f80746.png)

**Comment by jgabry** [comment]
Yeah no touching! But on the plus side I had forgotten about that scene so
I had a good chuckle.

**Comment by tjmahr** [comment]
Fixed in 0d12c80399d04e22bf6d1cb630ea74b20c333776

**Comment by jgabry** [comment]
Great, thanks TJ!
