### ISSUE TITLE
narrow mcmc_areas_ridges inner intervals have problems

### ISSUE THREAD

**Issue by tjmahr** [stan-dev/bayesplot#126]
The plot draws the vertical line if applicable, then draws the outer ridge line (no fill), then draws the inner ridge line (filled). When the inner interval is small, we get some weirdness:

![image](https://user-images.githubusercontent.com/1890315/32955082-8845bd36-cb7a-11e7-8b56-cd7b78ace62c.png)

Reversing the draw order (inner then outer) is an improvement.

![image](https://user-images.githubusercontent.com/1890315/32955391-77a70f06-cb7b-11e7-8b27-b568a03793e1.png)

But ultimately, we need a "blank" fill on the outer interval for the points that land outside of the inner interval.

So 

- draw inner interval
- draw full outer interval with no fill
- draw outer interval where x <= min(inner$x) or max(inner$x) <= x with blank fill, inheriting the fill from the global plotting theme. (Consider though #120)

**Comment by tjmahr** [comment]
Here's how the fixed version will look. Solution proved to be kind of clumsy: We draw the density curves one at time working from top to bottom to ensure that overlapping areas are obscured.

![image](https://user-images.githubusercontent.com/1890315/32959986-f2fd64fe-cb88-11e7-9048-ddc5e4cded82.png)

I toyed with using a semi-transparent fill so the overlap would be communicated but that seemed too gimmicky.

**Comment by jgabry** [comment]
That does look much nicer visually. Bummer the fix is clumsy but definitely
worth it to avoid the ugly overlapping.
