### ISSUE TITLE
add visual unit tests for ppc distribution functions

### ISSUE THREAD

**Issue by tjmahr** [stan-dev/bayesplot#133]
When I did "my quick fix" the mcmc_areas issue (#125), I accidentally pushed commits from a branch where I was refactoring `ppc_` plots to use a `ppc_data()` helper (ae6e2d8b5395fcdb45e, d97e435ad34, c4e012bd7a935c819e7a). 

As far as I can tell, everything is fine, but I need to confirm this by creating visual unit tests that show that the plots have not changed.

**Comment by jgabry** [comment]
Ok thanks, no problem.

**Comment by jgabry** [comment]
closed via #137
