### ISSUE TITLE
Warning message when working with dataframes with "Chain" column

### ISSUE THREAD

**Issue by ermeel86** [stan-dev/bayesplot#160]
Hi,

using bayesplot 1.5.0 when I run the following code
```r
library(bayesplot)
library(tibble)
set.seed(42)
df <- tibble::tibble(parameter=rnorm(n=1000), Chain=rep(1:10, each=100))
bayesplot::mcmc_dens_chains(df, par=c("parameter"))
```

I get the warning

```
Warning message:
Unknown or uninitialised column: 'chain'. 
```

The manual says one can work with a "Chain" column. Why does the warning asks for a "chain" column?

The same happens for other bayesplot routines, like e.g. `mcmc_intervals`, `mcmc_areas`, `mcmc_hist` and `mcmc_violin`.

The warning disappears when I add a column `chain` (thus have `chain` and `Chain`), however just having one column `chain` will also give a warning due to missing column `Chain`.

It would be good to get rid of this warning message, since otherwise it seems to work as expected.

**Comment by jgabry** [comment]
Thanks for reporting this. That’s not an intentional warning. Not sure what’s causing it but I’ll try to reproduce it and we’ll look into it.

**Comment by jgabry** [comment]
I just checked and I also get this warning. @tjmahr Just creating the data 

```r
mcmc_dens_chains_data(df, par=c("parameter"))
```

is sufficient to trigger the warning, probably related to these lines:

https://github.com/stan-dev/bayesplot/blob/6537965507f32271257de763bc997050df04ac27/R/mcmc-distributions.R#L271-L273

**Comment by jgabry** [comment]
This is related to https://github.com/tidyverse/tibble/issues/450 and https://community.rstudio.com/t/bug-report-unknown-column-warning-when-using-tibbles/12246/8

**Comment by tjmahr** [comment]
Yeah, tibbles complain when we look up a name that isn't there. Normal dataframes don't.

``` r
df <- tibble::tibble(parameter=rnorm(n=1000), Chain=rep(1:10, each=100))
x <- bayesplot:::prepare_mcmc_array(df, "parameter")
#> Warning: Unknown or uninitialised column: 'chain'.
y <- bayesplot:::prepare_mcmc_array(as.data.frame(df), "parameter")
```

<sup>Created on 2019-05-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
