### ISSUE TITLE
wrong parameter names bug in mcmc_areas 

### ISSUE THREAD

**Issue by wwiecek** [stan-dev/bayesplot#162]
If users choose to pass MCMC matrix with parameter colnames as "integers string" (i.e. `colnames(mcmc_matrix) <- c("1", "2")` etc.; not a good idea to do it, but not illegal either), mcmc_areas gets very confused... or at least I think that's why I see things like this:
![image](https://user-images.githubusercontent.com/20645798/42687362-899ec6ce-8690-11e8-978a-d8cec1630ca8.png)

Minimal data here:
[mcmc_areas_bug.zip](https://github.com/stan-dev/bayesplot/files/2192278/mcmc_areas_bug.zip)
```r
ww <- readRDS('mcmc_areas_bug.rds')
bayesplot::mcmc_areas(ww) #polygon connecting the two
colnames(ww) <- c("a", "b")
bayesplot::mcmc_areas(ww) #all good
```

**Comment by bob-carpenter** [comment]
*Every* bug should be handled this way. 

1.  create a unit test that fails in the current develop branch
2.  fix it
3.  commit both test (which becomes a so-called "regression" test) and the fix

Then it doesn't creep back in as a bug later.

**Comment by tjmahr** [comment]
A different minimal example that doesn't need the data file from the original issue.

```r
library(bayesplot)
library(dplyr)
d <- example_mcmc_draws(chains = 1, params = 2) %>% 
  as.matrix() %>%
  as.data.frame() %>% 
  setNames(c("1", "2"))

# bad
mcmc_areas(d)

# good
colnames(d) <- c("a", "b")
mcmc_areas(d)

```

**Comment by tjmahr** [comment]
All of our MCMC data preparation run through our own function `melt_mcmc()` which wraps `reshape2::melt()`, a function that converts matrices/arrays/dataframes/tables/etc into long dataframes. It has the following argument:

 - `as.is` - if `FALSE`, the default, dimnames will be converted using `type.convert`. If `TRUE`, they will be left as strings.

So the columns named `"1"` and `"2"` are converted to integers via `type.convert()` here. Overriding this default should do the trick.
