### ISSUE TITLE
support for equal-height curves mcmc_areas()

### ISSUE THREAD

**Issue by tjmahr** [stan-dev/bayesplot#163]
A user was confused why some older `mcmc_areas()` plots changed from version 1.4.0. 

In that update, I changed `mcmc_areas()` so that all the density curves had the same area. (I *think* they have the same area.) So a wider interval would have a wide, thin density and a shorter interval is more of a spike. 

```r
library(bayesplot)
library(ggplot2)
library(dplyr, warn.conflicts = FALSE)

example_data <- bayesplot::example_mcmc_draws(params = 6)

d <- mcmc_areas_data(example_data, c("beta[1]", "beta[2]", "beta[3]")) %>%
  mutate(
    interval = factor(interval, c("outer", "inner", "point")))

ggplot(d) +
  aes(x = x, y = parameter, fill = interval, height = density) +
  ggridges::geom_density_ridges(stat = "identity", scale = 0.90) +
  scale_fill_brewer(type = "seq", palette = 2) +
  guides(fill = FALSE) +
  ggtitle("curves have same area") +
  scale_y_discrete(
    limits = unique(rev(d$parameter)),
    expand = expand_scale(mult = c(.05, .5)))
```

![image](https://user-images.githubusercontent.com/1890315/44301906-e7ccc500-a2e4-11e8-9e94-e363d053f086.png)

In the old behavior of `mcmc_areas()` the densities were scaled to have the same max height. We can easily recover this behavior.  

```r
# rescale density within each parameter to be proportion of max density
d <- d %>%
  group_by(parameter) %>%
  mutate(scaled = density / max(density)) %>%
  ungroup()

ggplot(d) +
  aes(x = x, y = parameter, fill = interval, height = scaled) +
  ggridges::geom_density_ridges(
    stat = "identity",
    scale = 0.90) +
  scale_fill_brewer(type = "seq", palette = 2) +
  guides(fill = FALSE) +
  scale_y_discrete(
    limits = unique(rev(d$parameter)),
    expand = expand_scale(mult = c(.05, .5))) +
  ggtitle("curves have same height")
```

![image](https://user-images.githubusercontent.com/1890315/44301925-4b56f280-a2e5-11e8-92e6-eeb79e0cc5c7.png)

Both styles have their benefits. The first helps compare rows. The second helps show the curvature within rows.

To fix this,

- `mcmc_areas_data()` should also return a `scaled_density` column
- `mcmc_areas()` should get an `equalize_by` argument with `"area"` `"height"` as options.
- `mcmc_areas()` should also take a `area_scale` parameter to pass onto `ggridges::geom_density_ridges()` for customization.

**Comment by bob-carpenter** [comment]
By scaling the x-axes, you can have every row be the same height and area, but then the locations and scales get distorted among the rows.

**Comment by tjmahr** [comment]
It looks like this came up at a recent Stan meeting. https://discourse.mc-stan.org/t/stan-meeting-aug-16-2018/5262

A third option is to scale the height by the square root of the height, as a compromise between to two.

**Comment by jgabry** [comment]
@tjmahr I agree it would be preferable to support multiple options for `mcmc_areas()`. It's probably worth making all three of the proposed options available.
