### ISSUE TITLE
Fixing the density estimation for ppc_loo_pit_overlay

### ISSUE THREAD

**Issue by GustafRydevik** [stan-dev/bayesplot#171]
The tendency of the density estimation to go down at the edges can cause confusing graphs, especially for situations where the data set is small. Would it be possible to change this to use a boundary-corrected kernel density estimator, such as kde.boundary in  https://cran.r-project.org/web/packages/ks/ or bckden in https://rdrr.io/cran/evmix/man/bckden.html ?

**Comment by avehtari** [comment]
This has been on our todo list, but not with high priority. If you have tried either of these function you propose, it would be great if you can include an example of how to use them and how the plot would look like for an uniform data.
