### ISSUE TITLE
Missing links in documentation

### ISSUE THREAD

**Issue by lgaborini** [stan-dev/bayesplot#174]
Hi, I was skimming through the bayesplot online documentation.

Apparently there are some really useful pages which are quite hidden from the index. One has to go through the documentation for specific functions.

I am referring to this page (but there might be others):
http://mc-stan.org/bayesplot/reference/MCMC-overview.html

It does not appear in the index, vignettes and function lists, yet it describes which data formats are accepted.     
I'd put that in a dedicated vignette (something like "Interfacing to MCMC outputs"), or I'd make that appear in the Reference section.

**Comment by jgabry** [comment]
Thanks for the recommendation and sorry for the slow reply! 

The MCMC-overview page is linked to from the documentation for every function with an `mcmc_` prefix. For example, if you do `help("mcmc_hist")` from R or go to http://mc-stan.org/bayesplot/reference/MCMC-distributions.html#arguments then the doc for the first argument `x` says: 

"A 3-D array, matrix, list of matrices, or data frame of MCMC draws. The [MCMC-overview](http://mc-stan.org/bayesplot/reference/MCMC-overview.html) page provides details on how to specify each these allowed inputs."

But you're right that MCMC-overview (and the analogous PPC-overview) doesn't appear to have its own link directly from the function reference home page at http://mc-stan.org/bayesplot/reference/index.html. I hadn't noticed that and will try to add that when we do the next release. Thanks again for pointing that out!

**Comment by jgabry** [comment]
These should now appear in the reference section. Thanks again for pointing this out.
