### ISSUE TITLE
Always call `as.matrix` or `as.array` on the first argument

### ISSUE THREAD

**Issue by bgoodri** [stan-dev/bayesplot#175]
If I have a stanreg object called `post`, then 
```
bayesplot::mcmc_acf(post)
```
should just work, but it doesn't because the first argument is neither a matrix nor an array. But when no specific method is defined for stanreg objects, the **bayesplot** functions should just call `as.matrix` or `as.array` on the first argument internally, like `apply` and things like that do. That way we can accept anything that can be coerced into a matrix or an array without having to write methods for everything.

**Comment by jgabry** [comment]
Coming back to this now that I have some time to work on the next bayesplot release. @tjmahr, this seems like a good idea to me. Any reason you can think of not to do this?

**Comment by tjmahr** [comment]
So if x is not an array or matrix, we try calling `as.array()` on it when we run `prepare_mcmc_array()`? And something similar for when we need matrices? Can we some additional check that tells us whether the result of as.array() is appropriate for later work? 

Like, both of these return something after `as.array()`, but only one of them will has the right structure for plotting.

```
fit <- rstanarm::stan_glm(mpg ~ ., data = mtcars, iter = 50)
fit2 <- lm(mpg ~ ., data = mtcars)
```

**Comment by jgabry** [comment]
Good point. Maybe we can just check the result of calling `dim` on the object returned by `as.array(...)`. We would need the resulting object to have either 2 or 3 dimensions (2 if all chains combined, 3 if separate). In the example above `dim(as.array(fit))` returns the vector `c(25, 4, 12)`, which is fine, but `dim(as.array(fit2))` returns just `12`, so it's just a 1-D array and we could reject it.

**Comment by tjmahr** [comment]
> We would need the resulting object to have either 2 or 3 dimensions (2 if all chains combined, 3 if separate). 

I like that.

**Comment by bgoodri** [comment]
If some package has a specialized method, then it should definitely
dispatch to that. The default method should just allow the function to work
without a specialized method whenever that makes sense. In cases where it
can't make sense, it doesn't work currently so this is just an opportunity
to throw a better error message.

**Comment by tjmahr** [comment]
Right.

- as.array() on a valid array... safe
- as.array() on an object with an as.array() method... safe. 
- as.array() on anything else... as.array.default() adds a dim attribute. we reject if it doesn't have valid dimensions.
