### ISSUE TITLE
Add colorblind safe and printer friendly options to color_scheme_set

### ISSUE THREAD

**Issue by VeenDuco** [stan-dev/bayesplot#177]
It would be nice to have colorblind safe and printer friendly options to choose with the  `color_scheme_set()` function. Options for this can be found via [here](http://colorbrewer2.org/#type=diverging&scheme=RdBu&n=6).

One option that would satisfy both critera is the color scheme `#b2182b #ef8a62 #fddbc7 #d1e5f0 #67a9cf #2166ac`.

**Comment by tjmahr** [comment]
We do provide the [four viridis palettes](https://cran.r-project.org/web/packages/viridis/vignettes/intro-to-viridis.html), plus the fifth cividis palette has been added in a different branch. But maybe it could be easier to switch to Brewer palettes.

**Comment by avehtari** [comment]
> But maybe it could be easier to switch to Brewer palettes.

For backward compatibility it's good to keep the old ones, but it would be great to be able easily to choose from brewer palettes, too.

@VeenDuco which plot in bayesplot you were specifically thinking now?

**Comment by VeenDuco** [comment]
@avehtari I didn't have a specific plot in mind, I want to offer it as an option in shinystan for all plots which I would set using `color_scheme_set`.

**Comment by avehtari** [comment]
> I want to offer it as an option in shinystan for all plots which I would set using color_scheme_set.

I would list there all named Brewer palettes and the existing bayesplot palettes

**Comment by VeenDuco** [comment]
Allright, I will do that.

**Comment by jgabry** [comment]
We could certainly allow something along the lines of: 

```r
color_scheme_set("brewer-PuBuGn")
```

which would set the color scheme to six colors from the PuBuGn brewer palette. (I'm using palette names from https://moderndata.plot.ly/create-colorful-graphs-in-r-with-rcolorbrewer-and-plotly/). To do this we would need to do one of the following: 

* hardcode the palettes in the `master_color_list`:

https://github.com/stan-dev/bayesplot/blob/3922b87dd9cb9f3dc979b0e8de8e10149aee7dea/R/bayesplot-colors.R#L341-L346

* or add a dependency on the `RColorBrewer` package and use `RColorBrewer::brewer.pal()` to generate them on the fly. 

I think I would slightly prefer to just add the schemes to the `master_color_list`, but either way would work.

**Comment by jgabry** [comment]
@VeenDuco I can set up a branch of bayesplot with the brewer palettes so you can use that branch to test it out with the new shinystan stuff you are working on.

**Comment by jgabry** [comment]
Ok @VeenDuco go ahead and check out the `brewer-palettes` branch and PR #190

**Comment by jgabry** [comment]
I just deleted that branch so that won’t work anymore, but the PR was merged so you can just use the master branch.
