### ISSUE TITLE
Release v1.7.0?

### ISSUE THREAD

**Issue by jgabry** [stan-dev/bayesplot#197]
We haven’t done a release in a while and I think there’s enough stuff already merged since last release or almost merged that we should do a release pretty soon. It seems like there’s still decisions to made about the rank histograms, but we could release everything else in the meantime and get those out whenever they are ready. @tjmahr what do you think?

**Comment by tjmahr** [comment]
I'm putting last touches on the two rank plots

**Comment by jgabry** [comment]
We're passing on travis, win-builder (devel and release), and I'm running reverse dependency checks now. @tjmahr is there anything else you can think of that we should add/remove/change in the package before I go ahead and submit the next release to CRAN?

**Comment by tjmahr** [comment]
Nope.

**Comment by jgabry** [comment]
Ok cool! Once the revdep checks pass (or fail and I fix the issues) I'll go ahead and submit.

**Comment by jgabry** [comment]
Submitted. Will close the issue when accepted.

**Comment by jgabry** [comment]
On CRAN
