### ISSUE TITLE
`prob` argument can be in (-1, 0)?

### ISSUE THREAD

**Issue by wwiecek** [stan-dev/bayesplot#203]
Not important at all but I thought you might want to know. In 1.6.0 this works for me:

```
library(bayesplot)
set.seed(9262017)
x <- example_mcmc_draws(params = 6)
mcmc_areas(x, regex_pars = "beta\\[[1-3]", prob = -1) +
 ggplot2::labs(
   title = "Posterior distributions",
   subtitle = "with medians and 80% intervals"
 )
```

Same with `prob.outer`.
Setting `prob` to anything smaller than -1 produces the appropriate error:

**Comment by jgabry** [comment]
Thanks @wwiecek for reporting this and to @mcol for fixing
