### ISSUE TITLE
Possible to modify point size for mcmc_intervals?

### ISSUE THREAD

**Issue by adkinsty** [stan-dev/bayesplot#215]
Hello, I would like to adjust the point size of the point estimates from mcmc_intervals; is it possible to make them smaller? I apologize for the mundane question! Also, if there's a better place to ask questions like this, please let me know.

**Comment by jgabry** [comment]
Sorry for the 6 month delay! I missed this issue when it came in and just noticed we never responded. There's now a branch implementing this. More info here: https://github.com/stan-dev/bayesplot/issues/228
