### ISSUE TITLE
Question: Is the aesthetic mapping for the density histogram in mcmc_hist in the right place?

### ISSUE THREAD

**Issue by dpsimpson** [stan-dev/bayesplot#216]
With some warning, this might be a deeply stupid question that is out of step with good `ggplot2` practice, in which case please ignore it. 

**Context**
I want to overlay an `mcmc_hist` with a fixed density. This is really not an important use case, but I want it for teaching.

**The correct, but awkward (for me, at least) way**

The current code that will do that is  something  like
```
library(rstanarm)
library(bayesplot)
fit <- stan_glm(formula = y~1, data=data.frame(y=rnorm(100)))
mcmc_hist(fit,pars="(Intercept)",freq=FALSE) + 
  stat_function(aes(y = NULL), fun = dnorm, args = c(0,0.1))
``` 

The key thing is that I need the (to me unexpected) `aes(y=NULL)` because the ggplot object is initialized with (after parsing the `set_hist_aes` call)
```
ggplot(data, aes_(x = ~ value, y = ..density..))
```
Because of this, the following code (which seems more natural to me) breaks 
```
library(rstanarm)
library(bayesplot)
fit <- stan_glm(formula = y~1, data=data.frame(y=rnorm(100)))
mcmc_hist(fit,pars="(Intercept)",freq=FALSE) + 
  stat_function(fun = dnorm, args = c(0,0.1))
# Error: Aesthetics must be valid computed stats. Problematic aesthetic(s): y = ..density... 
# Did you map your stat in the wrong layer?
```

**A small change that fixes this**
If the plot is initialized with 
```
ggplot(data, aes_(x = ~ value))
```
and any local commands (like `aes_(y = ..density..)` ) is passed locally to `geom_histogram`, then the code works the way I would expect.  This also requires a change to `set_hist_aes`. Changes are here: https://github.com/dpsimpson/bayesplot/commit/39e6b12bd1cb7eb66a678cc9a9bb1f0994aa4b3c

**Does this hurt anything else**
I have not looked _super_ hard, but it looks roughly like this wouldn't break anything obvious. But I am happy to look properly.

** Question**
Is this a change worth making? Or is the current behaviour reasonable?

**Comment by tjmahr** [comment]
This is worth fixing and the solution here is mostly good.  Moving the placement of `set_hist_aes()` would be an easier and safer fix. (`set_hist_aes()` appears in ppc-distributions.R and ppc-errors.R.)

While we are at it, we should stop using the obscure, never-documented ..stat.. aesthetics and use the [new `stat()` conventions](https://ggplot2.tidyverse.org/reference/stat.html).

**Comment by dpsimpson** [comment]
Cool. Do you want me to make the changes and do a PR?

**Comment by tjmahr** [comment]
I have one going right now.
