### ISSUE TITLE
Default ggplot theme

### ISSUE THREAD

**Issue by jgabry** [stan-dev/bayesplot#22]
Decide what the default ggplot theme should be. See if Andrew has any comments / strong preferences.

**Comment by paul-buerkner** [comment]
My current preference is the brightblue color scheme, but also the red-blue mix could work well if the contrast between red and blue was increased.

**Comment by jgabry** [comment]
I'm still not sure about the default color scheme, but it doesn't really matter much. This issue was more about the underlying ggplot theme, which I think is pretty good for the moment so I'm going to close this
