### ISSUE TITLE
`expand_scale()` is deprecated; use `expansion()` instead

### ISSUE THREAD

**Issue by avehtari** [stan-dev/bayesplot#220]
e.g. mcmc_areas() warns now 
```
Warning message:
`expand_scale()` is deprecated; use `expansion()` instead. 
```
expand_scale has been used in ppc-loo.R and mcmc-intervals.R

**Comment by tjmahr** [comment]
Fixed in #219

**Comment by avehtari** [comment]
Thanks, @tjmahr . Just adding here that the fix has not yet been merged. So maybe we keep this issue open until it's merged?

**Comment by tjmahr** [comment]
That sounds good.

**Comment by jgabry** [comment]
I've been so busy with other stuff I didn't even see that PR! Will test and merge it ASAP. 

@tjmahr I think we need to release ASAP given the impending dplyr release. I'm thinking I'll do a minor release with just that fix and then hopefully get back to working more on bayesplot and making progress towards a release with more stuff. What do you think?

**Comment by tjmahr** [comment]
That's exactly what I think should happen. A patch in preparation for dplyr 1.0.0 (out on May 29, 2020).

**Comment by jgabry** [comment]
Ok great. 

Closing this now since I just merged Hadley's PR
