### ISSUE TITLE
proposed solution to travis always timing out

### ISSUE THREAD

**Issue by jgabry** [stan-dev/bayesplot#225]
travis is always timing out because of rstan (or its dependencies like BH). One way we could get around this is to only install packages listed in Depends and Imports and not bother installing suggested packages (rstan is a suggested package). Currently, doing this would cause a lot of our tests to fail because we use rstanarm in tests, but we could rewrite tests to avoid that. Assuming we can rewrite the tests, is there any other reason to not go with this approach?

**Comment by tjmahr** [comment]
What about GitHub actions?

**Comment by rok-cesnovar** [comment]
If you guys want, we can just plug the script we use for cmdstanr. It can be plugged in to any R package repo. Would take me 5min to set this up if you want to.

**Comment by jgabry** [comment]
That would be great!

**Comment by jgabry** [comment]
I should have thought of GitHub actions since we just did for CmdStanR! Looks like this will work. Will merge @rok-cesnovar's PR after the checks run one more time (I made a few tweaks). After that I'll update the other open PRs so that they get tested with the new system.
