### ISSUE TITLE
Feature request: allow changing size of credible interval lines and dot

### ISSUE THREAD

**Issue by quantumlinguist** [stan-dev/bayesplot#228]
When customizing the interval plot, I would like to be able to change the size of the interval lines and dot representing the median/mean because when you put the plot in Word lines/ dots are barely visible. Thanks

**Comment by jgabry** [comment]
I've added a preliminary version of this on a branch. If you install that branch of bayesplot using 

```r
devtools::install_github("stan-dev/bayesplot", ref = "mcmc_intervals-size")
```

then you should be able to use the new arguments `inner_size`, `outer_size`, and `point_size`. Does that do what you were looking for?

**Comment by quantumlinguist** [comment]
Yes, this is exactly what I needed! Thank you so much!

**Comment by jgabry** [comment]
Great, thanks for opening the issue!
