### ISSUE TITLE
PPC for (right-)censored data

### ISSUE THREAD

**Issue by fweber144** [stan-dev/bayesplot#233]
@paul-buerkner asked for an issue here on bayesplot's issue tracker concerning [brms's issue #967](https://github.com/paul-buerkner/brms/issues/967). So here it is. There's also a corresponding thread in [The Stan Forums](https://discourse.mc-stan.org/t/ppc-for-right-censored-data/17032).

That brms issue is a feature request for a PPC for right-censored data in parametric time-to-event models with a response distribution from which sampling is easy (e.g. log-normal or Weibull models). The suggestion is to compare the Kaplan-Meier estimate of the CCDF for the observed data to the posterior CCDFs. Section 4.4 ("Standardised survival probabilities") of the [preprint by Brilleman et al. (2020)](https://arxiv.org/abs/2002.09633) describes a similar PPC, however averaging over individual posterior CCDFs. This averaging over individual posterior CCDFs should not be necessary when sampling from the response distribution, which makes the approach suitable for brms's generic PPC framework. @jgabry suggested to integrate such a PPC into the bayesplot package where it may be accessed by other packages as well.

You may find some example code in [brms's issue #967](https://github.com/paul-buerkner/brms/issues/967).

**Comment by jgabry** [comment]
Thanks for opening the issue. I've been a bit swamped recently so I haven't had much time to think about this yet, but I definitely think it would be good to have PPCs for this in bayesplot. I'll try to respond with more soon!

**Comment by fweber144** [comment]
No problem, I don't have that much time either. But if it helps, I could try a PR. For this, it would be necessary to decide if you want to include this feature in the existing `bayesplot::ppc_ecdf_overlay()` function or if you want to create a new function for that. Including it in `bayesplot::ppc_ecdf_overlay()` will probably require a new argument accepting the event/censoring indicator and (if you want to use the code provided [here](https://github.com/paul-buerkner/brms/issues/967#issuecomment-663032952)) a back-transformation of the CCDFs to CDFs via "CDF = 1 - CCDF". I guess this back-transformation shouldn't be too difficult with ggplot2; I will check it out if I get the time.

**Comment by fweber144** [comment]
After taking a look at the source code of `bayesplot::ppc_ecdf_overlay()`, I think it's better to create a new function for the proposed PPC for (right-)censored data. Of course, the inclusion in `bayesplot::ppc_ecdf_overlay()` would be possible but in my opinion, it would require splitting up nearly the whole code of `bayesplot::ppc_ecdf_overlay()` into two separate cases (the current code for noncensored data and the new code for right-censored data). The back-transformation of the CCDFs to CDFs via "CDF = 1 - CCDF" would not be a problem: `ggfortify::autoplot.survfit()` has an argument `fun` which exactly allows for such transformations of the CCDF. However, when creating a new bayesplot function for this new PPC, I think it would be better to plot the *untransformed* CCDF (since in survival analyses, the CCDF is more common than the CDF).

**Comment by fweber144** [comment]
Besides, thanks to ggplot2, "deeper" customizations of the plots produced by `ggfortify::autoplot.survfit()` are possible, too. For example, here is some code for adding the typical "bayesplot PPC legend" to the code from [this comment in brms's issue #967](https://github.com/paul-buerkner/brms/issues/967#issuecomment-663032952). The first possibility is to modify the ggplot2 data returned by `ggfortify::autoplot.survfit()`:
```r
data_ppc_gg <- ppc_km_overlay$data
data_ppc_gg$strata <- as.factor(ifelse(grepl("^draw", data_ppc_gg$strata), "y_rep", "y"))
ppc_km_col_mod <- c("y" = "black", "y_rep" = "gray")
ppc_km_overlay_mod <- ggplot(data = data_ppc_gg,
                             mapping = aes(x = time, y = surv, color = strata, group = group)) +
  geom_step() +
  scale_y_continuous(labels = scales::percent) +
  scale_color_manual(name = NULL, values = ppc_km_col_mod) +
  coord_cartesian(ylim = c(0, 1))
print(ppc_km_overlay_mod)

```
![PPC_autoplot_large_legend](https://user-images.githubusercontent.com/55132727/89272575-a43d0400-d63e-11ea-9e58-5921e20718ae.png)

The second possibility is to use `ggfortify::fortify.survfit()`:
```r
fortify_ppc <- fortify(sf_ppc)
fortify_ppc$group <- fortify_ppc$strata
fortify_ppc$strata <- as.factor(ifelse(grepl("^draw", fortify_ppc$strata), "y_rep", "y"))
ppc_km_overlay_fortify <- ggplot(data = fortify_ppc,
                                 mapping = aes(x = time, y = surv, color = strata, group = group)) +
  geom_step() +
  scale_y_continuous(labels = scales::percent) +
  scale_color_manual(name = NULL, values = ppc_km_col_mod) +
  coord_cartesian(ylim = c(0, 1))
print(ppc_km_overlay_fortify)

```
![PPC_fortify_large_legend](https://user-images.githubusercontent.com/55132727/89272556-9dae8c80-d63e-11ea-9497-a555ce8eb116.png)

Note that in contrast to `ggfortify::autoplot.survfit()`, `ggfortify::fortify.survfit()` does not add the survival proportion 1 at timepoint 0. Sooner or later, adding the survival proportion 1 at timepoint 0 might cause problems in the general context of bayesplot. Taking the more conservative approach of `ggfortify::fortify.survfit()` (not adding the survival proportion 1 at timepoint 0) would be preferable for bayesplot, I think.

**Comment by jgabry** [comment]
> But if it helps, I could try a PR.

That would be great! Let me know if you have any questions related to the bayesplot source code. 

> After taking a look at the source code of `bayesplot::ppc_ecdf_overlay()`, I think it's better to create a new function for the proposed PPC for (right-)censored data.

Yeah I think you're right about making a new function. 

The example plots look good! I don't deal with these kinds of models a lot so I'm inclined to trust your judgement on the details. 

Thanks again for bringing this up and working on it!
