### ISSUE TITLE
Check that all plot text is correct (e.g. titles, axis labels, etc.)

### ISSUE THREAD

**Issue by jgabry** [stan-dev/bayesplot#24]
Also add any necessary or useful text that's missing

**Comment by paul-buerkner** [comment]
I have checked all pp_check plots and only have two minor suggestion: 

1. In `ppc_resid_binned`, the y-axis label says "Average Residual" but wouldn't "Average Residuals" be more consistent?
2. In `ppc_ts*` and `ppc_vs_x*` one might want to add a legend indicating that `y` is displayed by the lines / dots similar to how it is done in `ppc_violin_grouped`.

**Comment by jgabry** [comment]
Yes to both, thanks!

**Comment by jgabry** [comment]
* [x] Fix y-axis label in `ppc_resid_binned`
* [x] Fix facet labels in `ppc_resid`
* [ ] Add legend to `ppc_ts*` and `ppc_vs_x*`

**Comment by jgabry** [comment]
### Text in ppc plots
* [x] Fix y-axis label in `ppc_resid_binned`
* [x] Fix facet labels in `ppc_resid`
* [ ] Add legend to `ppc_ts*` and `ppc_vs_x*` 

### Text in mcmc plots
still needs checking

**Comment by paul-buerkner** [comment]
I have checked the mcmc_plots and have a few suggestions:

1. `mcmc_hist_by_chain` uses the same y axis for all parameters, which may lead to strange looking densities (try it with `example_mcmc_draws()`). Similarily, `mcmc_areas` uses the same x-axis, which again may look strange. (for `mcmc_intervals` using the same x-axis not a problem from my perspective)
2. The visualization of the point estimate in `mcmc_areas` only goes to the middle of the density. I think it looks better to display it completely from the bottom to the top of the density.
3. In `mcmc_neff_hist` the colors overlay each other at the borders.
4. In `mcmc_nuts_*` you write `accept_stat__` and `treedepth__`. Are those many underscores necessary when displayed in the plot?
5. `mcmc_nuts_energy` fails with `Aesthetics must be either length 1 or the same as the data (1): fill, colour, x`

**Comment by jgabry** [comment]
Thanks Paul, I'll try to get to these today. Much appreciated.

**Comment by jgabry** [comment]
@paul-buerkner It's not clear to me how to deal with the issue you raise about `mcmc_hist_by_chain`. Try this: 

```r
x <- example_mcmc_draws()
data <- reshape2::melt(x, value.name = "Value")
graph <- ggplot(data, aes(x = Value, y = ..density..)) +
  geom_histogram()

graph + facet_grid(Chain ~ Parameter, scales = "fixed")
graph + facet_grid(Chain ~ Parameter, scales = "free")
graph + facet_grid(Chain ~ Parameter, scales = "free_y")
graph + facet_grid(Chain ~ Parameter, scales = "free_x")
```
None of the different `scales` settings creates a plot that is equally readable for all parameters.

**Comment by jgabry** [comment]
Also, I'm not seeing that failure with `mcmc_nuts_energy`. Do you have an example?

**Comment by jgabry** [comment]
For (2): 

should be taken care of by 3971db42d2ae57bafdfcba3b3167478c8b964c7c

**Comment by jgabry** [comment]
For (3): 

I'm not sure why this is happening. You? It might be that unless the binwidth is really tiny there is going to be some overlap at the cutoff points for where the color changes.

**Comment by jgabry** [comment]
For (4): 

No, we don't need the underscores, I was just trying to be consistent with how we usually write them. I'm undecided on whether to keep them or remove them.

**Comment by paul-buerkner** [comment]
(1). You are right. We won't be able to achieve this with facet_grid, since rows are indicating chains not parameters. Accordingly, we will have to leave it as it is I guess.

(3) I have no idea and it is only a minor issue anyway and likely nothing that can be changed outside of ggplot... 

(4) I was seeing that you write log-posterior instead of lp__ so I thought, you might also want to change the other names. I am fine with both of course.

(5) After updating all of my packages the error went away.

**Comment by jgabry** [comment]
(1) Even if we swapped it so that rows were parameters and columns were chains (i.e. `Parameter ~ Chain` in the facet formula) it wouldn't work either. So I guess we either leave it as, get rid of the plot entirely (I'm not even sure how useful it is), or put in the documentation that it doesn't work well if you show parameters with large uncertainties and small uncertainties in the same plot. Preference?

(3) If it's confusing to have that overlap I could make the histogram all the same color and just put vertical lines at the points where the color currently changes. Do think it's preferable to do that or leave as is?

(4) Good point. Although it may actually make the most sense to just change `log-posterior` back to `lp__` because it's almost always not really the log-posterior (just up to constant) 

(5) Ok great

**Comment by paul-buerkner** [comment]
(1) I would leave the plot as is but put a little note in the documentation.

(3) It's not confusing it is just not perfect. I prefer colored bars over vertical lines though, so leave it as is for now. 

(4) As long as you explain all the technical parameter names in the doc, using `lp__` will be more consistent I guess. And technical names are ok for technical plots I guess.
