### ISSUE TITLE
ppc_loo_pit_qq() with 'compare = "normal"'

### ISSUE THREAD

**Issue by fweber144** [stan-dev/bayesplot#240]
Since `ppc_loo_pit_qq()` with `compare = "normal"` adds a straight line, I wonder if the line
https://github.com/stan-dev/bayesplot/blob/5500d2eecb6beff9ab1654d0a79bc9b591fad270/R/ppc-loo.R#L223
shouldn't better read
```r
pit <- as.vector(stats::qnorm(pit))
```
(and the documentation be adjusted accordingly).

**Comment by jgabry** [comment]
Hmm, yeah I see what you mean. @avehtari what do you think?

**Comment by avehtari** [comment]
Ok for me

**Comment by jgabry** [comment]
@fweber144 do you want to submit a PR for this? If you don't have time don't worry about, I'll try to do it before the next release.

**Comment by fweber144** [comment]
Done.

**Comment by jgabry** [comment]
Awesome, thanks @fweber144!
