### ISSUE TITLE
mcmc_intervals: add example of relabeling without changing order

### ISSUE THREAD

**Issue by jscamac** [stan-dev/bayesplot#242]
Hi, I'm attempting to relabel the parameters in a `mcmc_interval` plot by adding a `ggplot2::scale_y_discrete(labels = new_labels)` approach.

The problem I'm having is that when I do this, the labels are correctly relabelled, but the order of the yaxis changes, such that the Intercept term now is at the bottom as opposed to the top (I prefer to have the intercept on top). I've played around with trying to set the breaks or inverting the limits of the axis but have had no success. Also because the mcmc plot functions make a variety of changes to the underlying data prior to plotting I don't really see an obvious way to set the order. Is there something obvious I'm missing here?

```
# MWE example
prior1 <- prior(normal(0,10), class = b) +
  prior(cauchy(0,2), class = sd)
fit1 <- brm(count ~ zAge + zBase * Trt + (1|patient),
            data = epilepsy, family = poisson(), prior = prior1)

# Default (no relabelling but correct order)
mcmc_intervals(fit1, regex_pars="b_"

# Relabelling (but order of pars changes)
mcmc_intervals(fit1, regex_pars ="b_") +
  ggplot2::scale_y_discrete(labels = c("b_Intercept" ="Intercept",
                                       "b_zAge" = "Age",
                                       "b_zBase" = "Base",
                                       "b_Trt1" = "Treatment",
                                       "b_zBase:Trt1" = "Base x Treatment"))
```

**Comment by jscamac** [comment]
Nevermind... I was obviously missing something:

The solution is:

```
mcmc_intervals(fit1, regex_pars ="b_") +
                 ggplot2::scale_y_discrete(labels = c("b_Intercept" ="Intercept",
                                                      "b_zAge" = "Age",
                                                      "b_zBase" = "Base",
                                                      "b_Trt1" = "Treatment",
                                                      "b_zBase:Trt1" = "Base x Treatment"),
                                           limits = c("b_zBase:Trt1",
                                                      "b_Trt1",
                                                      "b_zBase",
                                                      "b_zAge",
                                                      "b_Intercept"))
```

**Comment by jgabry** [comment]
Glad you found the solution! Just seeing this now but you ended up finding exactly what I would have a recommended. Is there something we could put in the doc that would have made it easier to figure this out? Or maybe we should just add an example of doing this to the Examples section in the doc?

**Comment by jscamac** [comment]
I think just add an example. You already have an example for changing the labels, you could just expand this to include the limits component. Maybe most people don't care, but I'm a bit OCD where I like to have parameters in a particular order (e.g. intercept always on top).
What confused me most, was I thought I'd be able to achieve the reordering using the `breaks` argument. But that doesn't seem to work.

While not directly related to this. Is it possible to change the line width of the point estimate in mcmc_areas(). I know this is possible in mcmc_interval but from my quick scan it doesn't appear to be possible in `mcmc_areas`.

Anyway thanks for the fantastic package. I've only just started using it, having normally coded up my own plotting functions, I can really see how it will significantly reduce the post-processing of these models in my workflow. Awesome work!

**Comment by jgabry** [comment]
> I think just add an example. You already have an example for changing the labels, you could just expand this to include the limits component.

Yeah that sounds good. I'm going to edit the title of this issue to reflect that the to-do item for us is to add an example. 

> What confused me most, was I thought I'd be able to achieve the reordering using the breaks argument. But that doesn't seem to work.

Hmm, yeah I see what you mean. 

> While not directly related to this. Is it possible to change the line width of the point estimate in mcmc_areas(). I know this is possible in mcmc_interval but from my quick scan it doesn't appear to be possible in `mcmc_areas`.

Not on the master branch yet but there's actually an open PR that adds this: https://github.com/stan-dev/bayesplot/pull/224. So you could install from the branch for that PR and it should work. In fact, it would be great to know if it works as intended if you try it out. 


> Anyway thanks for the fantastic package. I've only just started using it, having normally coded up my own plotting functions, I can really see how it will significantly reduce the post-processing of these models in my workflow. Awesome work!

Thanks, I really appreciate that! And yeah, that's exactly the goal of the package. One of the original motivations was that I found myself making the same sorts of plots over and over again so it seemed like a good idea to wrap them up into a package and let other people benefit from the code too. Of course for some kinds of plots it still makes sense to code them up individually, especially if a lot of customization is desired, but for plots that are common and helpful to look at during the workflow it's nice to have these single function calls that make the whole plot.
