### ISSUE TITLE
ppc_dens_overlay_grouped 

### ISSUE THREAD

**Issue by bnicenboim** [stan-dev/bayesplot#253]
Hi, I would really like to have `ppc_dens_overlay_grouped` in bayesplot.
 
Is it ok if I do a PR with this function? (It's super straightforward.)

**Comment by jgabry** [comment]
Yeah that would be nice to have. @tjmahr actually already has a PR open for this: https://github.com/stan-dev/bayesplot/pull/212, but we ran into an error in brms that prevented us from merging. I just commented over at that PR again to see if maybe we can move it along.

**Comment by jgabry** [comment]
> Is it ok if I do a PR with this function?

Since we have that open PR already I don't think we need another one, but in general yes! Happy to have to help out with bayesplot.

**Comment by bnicenboim** [comment]
ah, ok, looking forward for that then!

**Comment by jgabry** [comment]
@bnicenboim I just merged #212 so this function should now be available on the master branch if you want to use it.
