### ISSUE TITLE
mcmc_recover_hist with arrays shows the wrong order of the facets 

### ISSUE THREAD

**Issue by bnicenboim** [stan-dev/bayesplot#264]
`mcmc_recover_hist` messes the order of the parameters.

Reprex below:
```r
m <- '
data {
}
parameters {
  real<lower=0,upper=1> theta[25];
}
model {
  theta ~ beta(1,1);  // uniform prior on interval 0,1
}'

mstan <- cmdstan_model(write_stan_file(m))

fit <- mstan$sample(
  data = list(),
  seed = 123,
  parallel_chains = 4
)
```
This is fine:

```
mcmc_hist(fit$draws("theta"))
```

But here the order of the thetas is alphanumeric, rather than the order of the parameters
```
mcmc_recover_hist(fit$draws("theta"), rep(.5, 25))
```

version:
`bayesplot_1.8.0 `

**Comment by bnicenboim** [comment]
Ok, I just fixed it myself in https://github.com/stan-dev/bayesplot/pull/265
But BTW, why does the code of `mcmc_recover_hist` is so different from `mcmc_hist`?  I find it strange that it doesn't take advantage of `.mcmc_hist`, but so be it. I did a minor modification to fix it.

**Comment by mike-lawrence** [comment]
Same issues between `mcmc_recover_intervals()` and `mcmc_intervals()`; wrong order in the latter and oddly different outputs (coordinates flipped) between the two.
