### ISSUE TITLE
Add ECDF plot and ECDF difference plot with simultaneus confidence intervals as graphical goodness-of-fit and convergence diagnostics

### ISSUE THREAD

**Issue by TeemuSailynoja** [stan-dev/bayesplot#267]
As requested by @avehtari and @hyunjimoon, implement the ecdf plots from [this article](https://arxiv.org/abs/2103.10522). Code for the article is available [here](https://github.com/TeemuSailynoja/simultaneous-confidence-bands/blob/main/ecdf_plot_functions.R), so mostly cleaning and formatting needed.

**Comment by jgabry** [comment]
This would be great!

**Comment by hyunjimoon** [comment]
Wow thanks, Teemu! I have seen different versions of binomial/beta confidence intervals so having this included in bayesplot would be a great help to users being less confused about SBC overall.

**Comment by TeemuSailynoja** [comment]
Closed by #282
