### ISSUE TITLE
Add support for rvars draws format

### ISSUE THREAD

**Issue by avehtari** [stan-dev/bayesplot#274]
To avoid need for manually switching between different draws formats, it would be nice if bayesplot functions would allow draws_rvars format as input. At least `mcmc_hist` already works with draws_array, draws_matrix and draws_df.

**Comment by jgabry** [comment]
Yeah I agree. I haven't had much time for bayesplot lately but I'd like to find the time to do a release. There are a bunch of open pull requests and some easy issues like this one that could go in a new release.

**Comment by jgabry** [comment]
@Ozan147 the function that I think needs to be modified to support the posterior formats is `prepare_mcmc_array()`: 

https://github.com/stan-dev/bayesplot/blob/60edc5aa31bd58657eb8aac59305fa449f61316e/R/helpers-mcmc.R#L8
