### ISSUE TITLE
ppc_loo_* consistency

### ISSUE THREAD

**Issue by avehtari** [stan-dev/bayesplot#294]
`ppc_loo_intervals` and `ppc_loo_ribbon` have optional `psis_object` argument, but other `ppc_loo_*` functions don't. It would be nice if all of them would accept `psis_object` argument

**Comment by jgabry** [comment]
Yeah I agree

**Comment by avehtari** [comment]
I can fix this, but to not break anything I assume the other `ppc_loo_*` functions need to still keep `lw` argument. What should happen if both are given?

**Comment by jgabry** [comment]
Thanks. Is there any reason to supply both? If not then maybe an error saying only one should be supplied.

**Comment by jgabry** [comment]
Actually I'm working on the next bayesplot release now (to make sure we stay compatible with ggplot2, thanks for tagging me on that). So I can fix this issue too. 

What's strange is that I just noticed `ppc_loo_ribbon` has the `lw` argument but doesn't use it for anything. For `ppc_loo_intervals` and `ppc_loo_ribbon` it should be either `intervals` or `psis_object`, there's no need for `lw`. Anyway, I'll fix that along with adding the optional `psis_object` argument to the other functions.

**Comment by jgabry** [comment]
And actually if both are given I guess we don't need to error, we can just use `lw` since that will skip the step of extracting the weights from the psis_object. 

I'll work on this now.
