### ISSUE TITLE
ppc_loo_pit_qq theoretical line

### ISSUE THREAD

**Issue by avehtari** [stan-dev/bayesplot#296]
ppc_loo_pit_qq() currently adds a theoretical line that is not going from [0,0] to [1,1] but something else (maybe a line that passes through first and third quartiles?). When plotting pit values, the axes in the plot don't have a box corner at [0,0] and [1,1] and it is difficult to see where the line is going and it may look like as it would be the line from [0,0] to [1,1]. As in other rank ECDF plots the line is from [0,0] to [1,1], it would be if ppc_loo_pit_qq() would also plot a line from [0,0] to [1,1]

**Comment by jgabry** [comment]
Yeah, good idea!
