### ISSUE TITLE
Error during installation of 1.10.0

### ISSUE THREAD

**Issue by e5c** [stan-dev/bayesplot#297]
Hi, I get the below error when installing the latest version of bayesplot:

```
trying URL 'https://cloud.r-project.org/src/contrib/bayesplot_1.10.0.tar.gz'
Content type 'application/x-gzip' length 4993447 bytes (4.8 MB)
==================================================
downloaded 4.8 MB

* installing *source* package ‘bayesplot’ ...
** package ‘bayesplot’ successfully unpacked and MD5 sums checked
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
Error in element_line(linewidth = 0.3) : 
  unused argument (linewidth = 0.3)
Error: unable to load R code in package ‘bayesplot’
Execution halted
ERROR: lazy loading failed for package ‘bayesplot’
* removing ‘/local_disk0/.ephemeral_nfs/cluster_libraries/r/bayesplot’

The downloaded source packages are in
	‘/tmp/RtmpC8AdSC/downloaded_packages’
Warning message:
In install.packages(args[1], repos = args[2], lib = args[3]) :
  installation of package ‘bayesplot’ had non-zero exit status
```

However installation of `1.9.0` completes without error: 

```
require(devtools)
install_version("bayesplot", version = "1.9.0", repos = "http://cran.us.r-project.org")
```

Thanks!

**Comment by bbjohnson6810** [comment]
I just had the same issue (same 'linewidth' error) whether trying a basic installation, from source, or from github. 1.9.0 ended up working for me as well. Hopefully it's an easy fix!

**Comment by jgabry** [comment]
Sorry about this! Definitely my fault. Does it work if you update to the
latest ggplot2 version? I think the issue is that I forgot to add a check
for the user’s ggplot2 version before using the new `linewidth` argument
they added in the latest release.

**Comment by e5c** [comment]
Hi @jgabry , the bayesplot 1.9.0 installed with ggplot2 v 3.4.0, which I believe is [the latest](https://cran.r-project.org/web/packages/ggplot2/index.html).

**Comment by bbjohnson6810** [comment]
@jgabry I didn't when I got the error, but after updating ggplot2, looks like the most recent bayesplot installed just fine!
