### ISSUE TITLE
deprecated stat(density)

### ISSUE THREAD

**Issue by rstraete73** [stan-dev/bayesplot#301]
Dear,

I just received the warning message below when running in R4.2.2, RStudio Pro 2022.12.0 Build 353.pro20.

Kr,
Roel

>   plot(map.INTERNAL)
$mixdist

$mixdens

$mixecdf

$mix

Warning message:
`stat(density)` was deprecated in ggplot2 3.4.0.
ℹ Please use `after_stat(density)` instead.
ℹ The deprecated feature was likely used in the bayesplot package.
  Please report the issue at <https://github.com/stan-dev/bayesplot/issues/>.
This warning is displayed once every 8 hours.
Call `lifecycle::last_lifecycle_warnings()` to see where this warning was generated.

**Comment by jgabry** [comment]
I believe all uses of stat(density) were changed a while ago but I overlooked closing this issue. Thanks for reporting this a while ago.
