### ISSUE TITLE
Extend ppc_pit_ecdf and ppc_pit_ecdf_grouped to handle discrete data

### ISSUE THREAD

**Issue by TeemuSailynoja** [stan-dev/bayesplot#315]
The current PIT computation in `ppc_pit_ecdf` and `ppc_pit_ecdf_grouped` only works for continuous values.
Implementing randomized PIT, see, e.q., [Czado et al. (2009)](https://onlinelibrary.wiley.com/doi/10.1111/j.1541-0420.2009.01191.x) Eq.1, would extend the functions for discrete valued data.

At the same time, I could add axis labels and make the confidence bands dashed lines, as they are now too prominent.
- [ ] Implement randomized PIT.
- [ ] Add axis labels.
- [ ] Make confidence band lines dashed.

**Comment by TeemuSailynoja** [comment]
I have this mostly done, as I have needed this functionality with @avehtari in a few occasions, so I would just need to add it to a PR.

**Comment by jgabry** [comment]
Closing now that #316 was merged. Or are there still things to do? If so we can reopen.
