### ISSUE TITLE
Facets argument of facet_grid() deprecated

### ISSUE THREAD

**Issue by joannalingzj** [stan-dev/bayesplot#322]
Hi, 
I was running mcmc_acf and got this warning message.
mcmc_acf(posterior_b5, pars = c("b_Intercept","b_time","sd_Batch__Intercept","sd_Batch__time","sigma"), lags = 20)
Warning message:
The `facets` argument of `facet_grid()` is deprecated as of ggplot2 2.2.0.
ℹ Please use the `rows` argument instead.
ℹ The deprecated feature was likely used in the bayesplot package.
Please report the issue at <https://github.com/stan-dev/bayesplot/issues/>.
This warning is displayed once every 8 hours.
Call `lifecycle::last_lifecycle_warnings()` to see where this warning was generated. 

> lifecycle::last_lifecycle_warnings()
[[1]]
<warning/lifecycle_warning_deprecated>
Warning:
The `facets` argument of `facet_grid()` is deprecated as of ggplot2 2.2.0.
ℹ Please use the `rows` argument instead.
ℹ The deprecated feature was likely used in the bayesplot package.
  Please report the issue at <https://github.com/stan-dev/bayesplot/issues/>.
---
Backtrace:
    ▆
 1. └─bayesplot::mcmc_acf(...)
 2.   └─bayesplot:::.mcmc_acf(...)
 3.     ├─base::do.call(facet_fun, facet_args)
 4.     └─ggplot2::facet_grid(facets = "Chain ~ Parameter")
 5.       └─ggplot2:::deprecate_warn0("2.2.0", "facet_grid(facets)", "facet_grid(rows)")

**Comment by jgabry** [comment]
Thanks for reporting this!

**Comment by jgabry** [comment]
Coming back to this, I think this was actually fixed in https://github.com/stan-dev/bayesplot/pull/305/. So it shouldn't produce a warning in the latest version of bayesplot. If it still does we can reopen this and look into it.
