### ISSUE TITLE
can't replicate vignette plots for mcmc_rhat and mcmc_neff

### ISSUE THREAD

**Issue by adcascone** [stan-dev/bayesplot#327]
Hello,

I'm trying to recreate the plots in the ["Visual MCMC diagnostics using the bayesplot package"](https://mc-stan.org/bayesplot/articles/visual-mcmc-diagnostics.html#effective-sample-size) - specifically those under the ['mcmc_rhat, mcmc_rhat_hist' section](https://mc-stan.org/bayesplot/articles/visual-mcmc-diagnostics.html#mcmc_rhat-mcmc_rhat_hist) and the ['mcmc_neff' section](https://mc-stan.org/bayesplot/articles/visual-mcmc-diagnostics.html#mcmc_neff-mcmc_neff_hist).

When I run this code in the vignette to reproduce the `mcmc_rhat()` output:
```
color_scheme_set("brightblue") # see help("color_scheme_set")
mcmc_rhat(rhats)
```

The resulting plot is missing the line/point in the legend for the first two bins:
![image](https://github.com/user-attachments/assets/0dd2d6f6-2516-4635-a81b-f30a434f7b0f)

I see the same behavior in the subsequent plot, when y-axis text is added to the plot.

And when I run this code in the vignette to reproduce the `mcmc_neff()` output: 

```
mcmc_neff(ratios_cp, size = 2)
```
The resulting plot is again missing a line/point in the legend:

![image](https://github.com/user-attachments/assets/b17a286d-0406-484d-bea6-398f99e688b8)

Is this behavior expected? I noticed there are no data points in the bins that are missing from the legend so the plot's interpretations are not technically impacted. That said, it seems odd to have an incomplete legend.

-- Here are the relevant details of my R session -- 
```
> sessionInfo()
R version 4.4.1 (2024-06-14)
Platform: x86_64-pc-linux-gnu
Running under: Ubuntu 22.04.4 LTS

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] bayesplot_1.11.1   shiny_1.8.1.1
```

-- 

Thanks for the guidance!
Arianna C.

**Comment by jgabry** [comment]
Thanks for reporting this. That's definitely not intentional! It's strange because I'm pretty sure this wasn't an issue in the past, so I wonder if something changed in ggplot2 at some point that's causing this. Maybe we just need to change how we're creating the legend to play nicely with a change in ggplot2.

**Comment by jgabry** [comment]
Ok I think this should be fixed by https://github.com/stan-dev/bayesplot/pull/328. I'll include this in the next release, but for now you can install the fixed version using from that GitHub branch using 

```r
remotes::install_github("stan-dev/bayesplot", ref = "fix-diagnostic-legends")
```

If you're able to try it out let me know if that fixes the issue for you. Thank you!
