### ISSUE TITLE
mcmc_rank_overlay: d_bin_counts doesn't contain rows for cases with n = 0

### ISSUE THREAD

**Issue by sims1253** [stan-dev/bayesplot#331]
See also: https://discourse.mc-stan.org/t/rank-plots-dont-save-you-from-symmetric-non-stationary-chains/37624

In my case the first 4 bins all have count of 100 for the second chain, so the first chain's rank plot begins at 501. I suppose this could be a design choice but I think there should be bin entries in case n= 0.

![image](https://github.com/user-attachments/assets/9e22a033-b224-4149-b137-b788819b9093)

**Comment by jgabry** [comment]
@sims1253 thanks, can you check if https://github.com/stan-dev/bayesplot/pull/332 fixes the issue for you? You can install that branch of bayesplot with: 

```r
remotes::install_github("stan-dev/bayesplot", ref = "rank-overlay-always-start-0")
```

**Comment by jgabry** [comment]
Great, thanks for checking
