### ISSUE TITLE
More functionality for residual plots

### ISSUE THREAD

**Issue by milkha** [stan-dev/bayesplot#40]
1 - It would be useful to have grouped residuals. For instance, ppc_resid_hist_group. This can tell us about the distribution of residuals at a finer level which can provide some insight into the fit of the model.

2 - Currently,  there is no way to change the x-axis in residual plots. For discrete variables on the x-axis, we might want to have a box-plot for the residuals for each point.

**Comment by jgabry** [comment]
Thanks for following up and opening the issues!

**Comment by jgabry** [comment]
* [ ] residuals by group
* [ ] residuals vs x variable
* [ ] residuals by time similar to `ppc_ts_grouped` (from #38)

**Comment by jgabry** [comment]
@milkha @rtrangucci fyi, i changed "residual" to "predictive error", which is more technically correct, in the documentation and also renamed functions `ppc_error_*` instead of `ppc_resid_*`.
