### ISSUE TITLE
divergent transitions on the bottom of traceplots

### ISSUE THREAD

**Issue by its-a-wonderful-wonderful** [stan-dev/bayesplot#42]
Is there a way to add to stan_trace() the ability to display divergent transitions on the bottom of traceplots? 

Thank you!

**Comment by jgabry** [comment]
Thanks for the suggestion. This should be doable with geom_rug but will
require having the divergence info in the right format. In terms of the
user interface, I think it could either

(a) be an argument to mcmc_trace (that's the underlying traceplot function
in the new bayesplot package that will eventually be called by stan_trace
when released), e.g.,

mcmc_trace(..., divergences = optional_object_containing_divergence_info)

in which case stan_trace in rstan could automatically supply the divergence
info to mcmc_trace

or

(b) be a function that returns an object that can be added to the ggplot
object created by mcmc_trace, e.g.,

mcmc_trace(...) + divergence_rug(info)

where info contains the divergece data, and stan_trace could handle that
for the user as well.

>

**Comment by jgabry** [comment]
A preliminary implementation of option (a) from above is now available on the branch named `feature/issue-42-trace-w-divergences`.
