### ISSUE TITLE
pandoc/pandoc-citeproc dependencies

### ISSUE THREAD

**Issue by imadmali** [stan-dev/bayesplot#49]
I would suggest changing `README.md` to,

> If you are not using RStudio and you get an error related to "pandoc" you will either need to install pandoc (e.g. `brew install pandoc`) and pandoc-citeproc (e.g. `brew install pandoc-citeproc`), or remove the argument build_vignettes=TRUE to avoid building the package vignettes.

or something that suggests you also need pandoc-citeproc otherwise `R CMD build` fails at the command line. The pandoc documentation was unclear that pandoc-citeproc requires a separate installation (i.e. it's not bundled in with `brew install pandoc`. (It's probably not that big of a deal if you don't mention it since I'm guessing most people are building packages via RStudio, but at least someone dealing with this issue might find their way here.)

**Comment by sakrejda** [comment]
Please don't assume everyone uses rstudio when writing installation
instructions!   Krzysztof

**Comment by jgabry** [comment]
Ok thanks Imad.

**Comment by dpastoor** [comment]
@jgabry do you know if it'd be possible to customize how the package is bootstraped. Something along the lines of

somewhat pseudocoding:

```r
if (!rmarkdown::pandoc_available()) {
    warning("pandoc not available, so package vignettes will not be built, please see the readme for instructions on how to install dependencies")
    build_vignettes <- FALSE
}

```

I'm not sure if there is a package installation hook that such a line could be dropped in.

**Comment by jgabry** [comment]
The instructions don't assume RStudio. There's even a sentence specifically
directed at people not using RStudio! (And it will be a better sentence
once I add Imad's suggestion.) The only thing assumed is that, if you
aren't using RStudio and still want the vignettes, then you have Pandoc or
can install it.

And that's for the GitHub version only. If installing from CRAN it
shouldn't matter at all.

**Comment by jgabry** [comment]
Thanks Devin. At a minimum I could add that to the code provided in the
installation instructions.
