### ISSUE TITLE
figures don't show in vignettes posted on CRAN

### ISSUE THREAD

**Issue by Emaasit** [stan-dev/bayesplot#54]
![bayesplot-figures](https://cloud.githubusercontent.com/assets/7738216/21084232/5afc2ea4-bfb5-11e6-98e8-b6eb605e2875.png)

**Comment by Emaasit** [comment]
I tested on firefox and chrome web browsers.

**Comment by jgabry** [comment]
Thanks. This has already been fixed on GitHub (#50, #51) and the images should render properly in the vignettes in the next release.
