### ISSUE TITLE
LOO predictive checks

### ISSUE THREAD

**Issue by avehtari** [stan-dev/bayesplot#72]
#### Summary:
Add LOO predictive chesks
- [x] LOO probability integral transformation (PIT) predictive check
- [x] plot of LOO predictive intervals vs. observations

#### Description:
Calibration of the marginal predictions can be checked with probability integral transformation (PIT) checks. LOO improves the check by avoiding the double use of data. See Marginal predictive checks in BDA3 p. 152-153. In addition visual predictive checking can be made by plotting LOO predictive intervals and the observations.

Example code for LOO-PIT (I assume visual predictive checking is close to current ppc plot)

```
data(radon)
y<-radon$log_radon
# Fit the first model
modelA <- stan_lmer(
    log_radon ~ floor + log_uranium + floor:log_uranium + (1 + floor | county),
    data = radon,
    cores = 4,
    iter = 2000,
    chains = 4)

# probability integral transformation (PIT)
# this would be more accurate using conditional cdf's N(y_i|mu^{(s)},sigma^{(s)}
log_likA<-log_lik(modelA, parameter_name = "log_lik")
psisA<-psislw(-log_likA)
predsA<-posterior_predict(modelA)
pitA<-array(0,ncol(predsA))
library(matrixStats)
for (i in 1:ncol(predsA)) {
    pitA[i]<- exp(logSumExp(psisA$lw_smooth[(predsA[,i]<=y[i]),i]))
}

# LOO-PITs should have uniform distribution
par(mfrow=c(1,2))
qqplot(pitA,runif(10000))

```

**Comment by jgabry** [comment]
@avehtari Were you thinking that __bayesplot__ would do these computations? Or should we just have the computations in __rstanarm__  and __bayesplot__ just makes the plot (taking the result of the computations as input)?

**Comment by avehtari** [comment]
@jgabry you can decide where they fit best. I just somehow thought the posterior predictive checks where part of bayesplot, but you could compute LOO PITs in rstanarm and plot them in bayesplot.

**Comment by jgabry** [comment]
The PPC plotting functions are part of bayesplot but they take y and yrep
as input, so the actual predictions are fed into bayesplot and not computed
within bayesplot. bayesplot does do computations with yrep (i.e. computing
all the summaries statistics it needs) but it doesn't generate the yrep
draws.

**Comment by avehtari** [comment]
So then it should be enough that we get loo yrep from issue stan-dev/rstanarm#159 ?

**Comment by jgabry** [comment]
Yeah exactly. For bayesplot we can just  that as input and return the plot.

**Comment by jgabry** [comment]
I meant "take that as input"

**Comment by jgabry** [comment]
`ppc_loo_pit` and `ppc_loo_intervals` are now implemented on the `ppc-loo` branch, although it requires the version of __loo__ on GitHub, not the CRAN version
