### ISSUE TITLE
ppc_bars fails on ordinal models

### ISSUE THREAD

**Issue by bgoodri** [stan-dev/bayesplot#85]
This example in `rstanarm::pp_check`

```
#' \donttest{
#' # Example of a PPC for ordinal models (stan_polr)
#' fit2 <- stan_polr(tobgp ~ agegp, data = esoph, method = "probit",
#'                   prior = R2(0.2, "mean"), init_r = 0.1)
#' pp_check(fit, plotfun = "bars", nreps = 200, prob = 0.5)
#' pp_check(fit2, plotfun = "bars_grouped", group = esoph$agegp, 
#'          nreps = 500, prob = 0.5)
#' }
```
fails with `ppc_bars expects only non-negative integers in 'y'`. Apparently, it is not coercing the factor to an integer vector.

**Comment by jgabry** [comment]
I think this is an rstanarm issue and not a bayesplot issue. That is,
rstanarm should be doing that kind of conversion before passing y to
bayesplot.

I thought it was doing that already (that example used to work) but I will
check and fix it. On my way to a meeting now but I'll take care of it after
that.

**Comment by jgabry** [comment]
Actually I think it's just a typo in the example. It works for me when I change the first call to `pp_check` to use `fit2` instead of `fit`

**Comment by bgoodri** [comment]
After I do that (and install the new bayesplot), I get

Error: Cannot convert objects of type `NULL` to `quosure`

from `ppc_bars_yrep_data` when it assigns `tab <-`

**Comment by jgabry** [comment]
I'll investigate.

**Comment by jgabry** [comment]
The code below does not result in an error when I run it. It still does for you? If so can you debug any further? I can't replicate it. 

```r
fit2 <- stan_polr(tobgp ~ agegp, data = esoph, method = "probit",
                  prior = R2(0.2, "mean"), init_r = 0.1)
pp_check(fit2, plotfun = "bars", nreps = 200, prob = 0.5)
pp_check(fit2, plotfun = "bars_grouped", group = esoph$agegp,
         nreps = 500, prob = 0.5)
```

**Comment by jgabry** [comment]
Have you updated rstanarm since I made a few commits earlier?
