### ISSUE TITLE
Make the bayesplot default theme optional?

### ISSUE THREAD

**Issue by gavinsimpson** [stan-dev/bayesplot#87]
At the moment, from what I can tell having only had a brief look at the code, you are hard coding the**bayesplot** `theme_default()` ggplot theme when each plot is created. This makes it tedious to override by the user (they must add their own `+ theme_foo()` layers to *every* plot they create). Further, from a previous Issue I understand this might not work in all cases in **bayesplot** as some plots are actually multiple plots arranged on the device.

Instead, you can use the `theme_set()` functionality of **ggplot2** to set the default theme when the package is attached. The **cowplot** package, for example, uses this to set its default theme. This requires an `.onAttach()` function to be defined in the package R source somewhere with the following:

```r
.onAttach <- function(libname, pkgname) {
  ggplot2::theme_set(bayesplot::theme_default())
}
```

All instances of `+ theme_default()` would also need to be removed.

Doing this won't change the output from plots *unless* a user decides to change the theme used with by their own explicit call to `theme_set()` *after* **bayesplot** is loaded.

**Comment by jgabry** [comment]
Hi Gavin, thanks for the suggestion! Will this proposed method result in
changing the plotting theme for any ggplot2 plot created by the user
regardless of whether or not it is from bayesplot? That was my original
motivation for not doing it this way, i.e. to try to keep bayesplot stuff
only affecting bayesplot stuff. If I'm wrong about that or if I'm right but
users don't mind that behavior then I'd be open to switching to what you
propose.

**Comment by gavinsimpson** [comment]
@jgabry Yes, you are right; setting the theme globally as I suggested will affect every plot made with ggplot unless the plot code explicitly overrides the theme. However, that's easily and trivially fixed by having the user call `theme_set()`.

If people have the pkg loaded (i.e. it's attached not just being imported from) it's probably because they want to use the package, so the number of people affected by my suggested change is likely low.

On the other hand the solution used in **bayesplot** isn't easy to work around; a user has to add `+ theme()` etc to each plot, if they can affect the theme at all.

If you were to flag the issue, as **cowplot** does in documentation and in the `README` etc, I doubt this change would cause too much grief, but it would make modifying the look and feel of the plots trivial.

**Comment by jgabry** [comment]
Ok I think I'm persuaded. Shouldn't be hard to change so I'll try to get it
in for the next release. Thanks for following up.

**Comment by jgabry** [comment]
PR #95 merged so closing this

**Comment by gavinsimpson** [comment]
Thanks for implementing this wish @jgabry!

**Comment by jgabry** [comment]
Thanks for suggesting it!
