### ISSUE TITLE
provide ppc_intervals_data() and ppc_ribbon_data()

### ISSUE THREAD

**Issue by tjmahr** [stan-dev/bayesplot#99]
This is a first step in resolving #97.  It would add the following new functions:

* `ppc_ribbon_data()`
* `ppc_ribbon_grouped_data()`
* `ppc_intervals_data()`
* `ppc_intervals_grouped_data()`

**Comment by tjmahr** [comment]
Actually, we don't need the grouped versions.

**Comment by jgabry** [comment]
Excellent. These would be a great start.

**Comment by jgabry** [comment]
You mean because we can just apply the non-grouped versions with each
group?

**Comment by tjmahr** [comment]
I refactored the internal `.ppc_intervals_data` function to do the right thing when there is a group variable and when there isn't a group variable.

```
ppc_intervals_data <- function(y, yrep, x = NULL, group = NULL, prob = 0.9, ...) {
  check_ignored_arguments(...)
  .ppc_intervals_data(y = y, yrep = yrep, x = x, group = group, prob = prob
  )
}
```

**Comment by jgabry** [comment]
Ok, great!

**Comment by jgabry** [comment]
Closing now that PR #101 is merged
